backend/prisma/schema.prisma, backend/src/auth/auth.service.ts, frontend/src/components/auth/LoginComponent.tsx, frontend/src/components/auth/SignupComponent.tsx, frontend/src/types/auth/LoginValidationSchema.ts, frontend/src/types/auth/SignupValidationSchema.ts
- ログインフォームからSQL文を代入してSQLインジェクションさらないよう特殊文字を弾く対策をした
- usernameをユニークデータに変更
- #198 
- #205 
```
ログインフォームでSQLを実行できるかを確認
同じusernameのユーザの作成を試みて、作成できないことを確認
```
- SQLインジェクションをざっと調べた感じ、SQL文を代入して不正ログインする攻撃みたいですが、実際に防げているはイマイチわからないかもですね、、
about : #182, #183 
close  #182, #183
=> SQLインジェクション対策とusernameをユニークデータに変更

backend/src/auth/auth.service.ts, backend/src/auth/dto/auth.dto.ts, backend/src/auth/strategy/ft.strategy.ts, backend/src/main.ts, frontend/src/components/auth/SignupComponent.tsx
- 画像サイズの大きさ制限（10MB）
- Signup時に出るエラーを解消、10回試してがエラーは出なかった
```
10MB以下の画像をアップロードして保存されているかprismaで確認 or 11MBの画像をアップロードしてエラー出るか（11MBの画像あんまないけど）
Signupを何回か繰り返してエラーが出るか確認
```
- Signupエラーはまだ出るかもしれないので、出たらコメントしてください
about : #198, #205  
close #198 , #205
=> 画像サイズの大きさ制限 & Signup エラーの解消

frontend/src/App.tsx, frontend/src/features/game/GameRouting.tsx
GameにおけるRoutingをコンポーネント化した
App.tsxで列挙していたroutingをGameRouting.tsxにまとめた。
GameのRoutingが今まで通りできていれば問題ありません。
about : #154
=> [Game] routingをコンポーネント化した

backend/src/chat/chat.controller.ts, backend/src/chat/chat.service.ts, frontend/src/components/chat/dm/ChatComponent.tsx, frontend/src/components/chat/dm/ChatFriendsComponent.tsx, frontend/src/components/chat/dm/ChatGroupComponent.tsx, frontend/src/components/chat/utils/SearchChannelDialog.tsx, frontend/src/components/chat/utils/UserParticipantsList.tsx
- Channelのパスワードをハッシュ化する
- OWNERが抜けてしまった時にOWNER権限を2番手に付与する
- チャンネルが0人になった時点で自動的にチャンネルを削除する仕様に変更
- #214 
- #215 
```
Channelを作成してprismaでパスワードがハッシュ化されてるか確認
OWNERが抜けた時にprismaで違う人がOWNERに昇格してるか確認
```
about : #219, #216, #217
close #219, #216, #217
=> Chatリファクタリング（パスワードハッシュ化、OWENRの後処理）

backend/src/chat/chat.controller.ts, backend/src/chat/chat.service.ts, backend/src/chat/dto/chat.dto.ts, frontend/src/components/chat/dm/ChatFriendsComponent.tsx, frontend/src/components/chat/group/ChannelEditDialog.tsx, frontend/src/components/chat/utils/ChatlogComponent.tsx, frontend/src/utils/chat/ChatAxios.ts
- ブロックしているユーザのメッセージを表示しない仕様に変更
- Channel編集画面の更新
- DMの相手がLeaveした時のエラー解消
- #215 
- #205
```
複数ユーザを作成
チャンネルを作成して所属して会話する
特定のユーザをポストマンでブロックする
ブロックしたユーザのメッセージが表示されていないか確認
```
about : #104 
see also : #224 
close #104 #224
=> 【Chat】ブロックしているユーザのメッセージを表示しない仕様に変更

backend/src/main.ts, backend/src/user/user.service.ts, frontend/src/components/profile/BlockButton.tsx, frontend/src/components/profile/FriendListButton.tsx, frontend/src/components/profile/UnblockButton.tsx, frontend/src/components/profile/UnfriendButton.tsx, frontend/src/features/profile/OtherPeopleProfile.tsx
Blockボタンを実装しました
Blockボタンを実装したので、prismaを確認しながらblockをしたときに、block listが変更されていることを確認してみてください。
またblockしたユーザーからのフレンド申請は受付できない仕様となっています。
unblockに関してもblockしたユーザーは可能なので、試してみてください。
about : #165 
close #165
=> [Profile]block周りの機能を実装

backend/src/user/user.controller.ts, backend/src/user/user.service.ts, frontend/src/components/profile/EditEmail.tsx, frontend/src/components/profile/FriendRequestButton.tsx, frontend/src/features/profile/MyProfile.tsx
emailを編集できるboxを作ったので、編集してみてほしい
emailに関しては既に他のuserで使っている人がいれば、エラーが出るようにしている
また@がなかったりしてもエラーが出るかどうかを確認する。
通常ケースでちゃんと編集されるかも確認してみてください
about : #218 
close #218
=> [Profile edit]Profile画面から自身のemailを編集できるようになった

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/auth/dto/auth.dto.ts, frontend/src/components/auth/LoginComponent.tsx, frontend/src/components/auth/LoginFormComponent.tsx, frontend/src/components/auth/TwoFactorDialog.tsx, frontend/src/components/profile/TwoFactorButton.tsx, frontend/src/features/profile/MyProfile.tsx
- 2faログイン、オンオフのボタンの設置
- #288 
```
2faなしでユーザ作成
profileで2fa onにする
prismaで確認
loginで2faが求められるか確認
```
about : #292 
see also : #293 
close #292, #293
=> 2faログイン、オンオフのボタンの設置

backend/src/game/game.gateway.ts
connect部分の機能の追加
まだ途中
- 次やるべきこと(新たなissue)があれば記載
- これの続き
gameしてみる
game中に接続を遮断すると
backendのログに遮断したuserの名前が出る
=> Game connect/issue286

backend/src/match/match.controller.ts, backend/src/match/match.service.ts, frontend/src/components/profile/FriendListButton.tsx, frontend/src/components/profile/MatchListButton.tsx, frontend/src/features/profile/MyProfile.tsx, frontend/src/features/profile/OtherPeopleProfile.tsx, frontend/src/hooks/match/useWueryMatch.ts
自分と他人のpageから戦績一覧が確認できるようになった
試合をしてみて、自分の試合一覧が表示されているかを確認してください
また他人のページに行っても同様に確認できるはずです
about : #251 
close #251
=> [Profile]自分と他人のpageから戦績一覧が確認できるようになった

backend/src/app.gateway.ts, backend/src/auth/auth.controller.ts, backend/src/game/game.controller.ts, backend/src/game/game.gateway.ts, backend/src/game/game.module.ts, backend/src/game/game.service.ts, frontend/src/App.tsx, frontend/src/features/game/CreateGameRoom.tsx, frontend/src/features/game/GameObserver.tsx, frontend/src/features/game/GamePlayer1.tsx, frontend/src/features/game/GamePlayer2.tsx, frontend/src/features/game/GameRouting.tsx, frontend/src/features/game/JoinInvitedRoom.tsx
- このプルリクで何をしたのか？
- 機能追加の背景や動機は？
- 次やるべきこと(新たなissue)があれば記載
about : #0
see also : #0
close #0
=> Game status/issue288

backend/src/game/game.gateway.ts
#301 の修正
- 次やるべきこと(新たなissue)があれば記載
about : #301 
see also : #0
close #301
=> Game.Gatewayで発生したバグ修正

Makefile
- docker-compose up --build -d
- docker-compose up --build
- docker-compose up -d
を追加
about : #304 
close #304
=> Makefileにルールを追加

frontend/src/components/profile/BlockButton.tsx, frontend/src/components/profile/EditEmail.tsx, frontend/src/components/profile/FriendRequestButton.tsx, frontend/src/components/profile/NotificationButton.tsx, frontend/src/components/profile/UnblockButton.tsx, frontend/src/components/profile/UnfriendButton.tsx, frontend/src/features/profile/MyProfile.tsx, frontend/src/features/profile/OtherPeopleProfile.tsx, frontend/src/features/profile/ProfileRouting.tsx
エラーをキャッチしてalertをするようにした
about : #277 
close #277
=> [Profile] try catchにalertを入れた

backend/src/auth/auth.controller.ts
- 42login時にリフレッシュトークンを発行する
- 42loginで再ログインしたときにSignupしていた不具合を解消
about : #306 
close : #306
=> 42login をしたときにリフレッシュトークンを発行する

frontend/src/components/auth/LoginComponent.tsx
- online status bug fix
about : #307 
close #307
=> online status bug fix

backend/src/game/game.gateway.ts, frontend/src/features/game/GamePlayer1.tsx, frontend/src/features/game/GamePlayer2.tsx
game途中中断の場合にされた側を/gameにリダイレクトする
=>  game途中中断の場合にされた側を/gameにリダイレクトする

frontend/src/components/profile/EditEmail.tsx, frontend/src/features/profile/MyProfile.tsx, frontend/src/types/PrismaType.ts
- emailが編集できると再ログイン時に再Signupとなるので42login時はemailが編集できないようにした。
- 次やるべきこと(新たなissue)があれば記載
about : #314 
close #314
=> 42login時はemailが編集できないようにする

backend/src/chat/chat.service.ts, frontend/src/components/chat/dm/ChatFriendsComponent.tsx, frontend/src/components/chat/group/ChannelListComponent.tsx, frontend/src/components/chat/utils/LeaveButton.tsx
Channel passwordをhash化+base64に変更
about : #321 
close #321
=> Channel passwordをhash化+base64に変更

frontend/src/features/game/GamePlayer1.tsx, frontend/src/features/game/GamePlayer2.tsx
/gameに遷移する際にreload しないuseNavigateを使用した
gameを通常通りplayしてみる
about : #327 
see also : #327  
close #327
=> #327[edit] edit change page

backend/src/chat/chat.controller.ts, backend/src/chat/chat.service.ts, frontend/src/components/chat/utils/AdminButton.tsx, frontend/src/components/chat/utils/SearchChannelDialog.tsx, frontend/src/hooks/chat/useMutationMessage.ts
protect channelのバグ
Muteが機能しないバグ
owner権限を付与できないバグ
=> [fix] chat bug fix

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/auth/dto/auth.dto.ts, frontend/src/components/auth/FtTwoFactorLogin.tsx
- 42loginで2回目以降二要素認証した場合、アクセストークンが発行されなかったので発行されるように修正
about : #332 
close #332
=> 42loginで二要素認証が2回目以降失敗する不具合の修正

backend/src/auth/auth.service.ts, frontend/src/components/auth/TwoFactorDialog.tsx
=> [fix] 2fa bug fix

backend/prisma/migrations/20230501055209_/migration.sql, backend/src/game/game.service.ts, frontend/src/features/game/JoinInvitedRoom.tsx
Gameでinviteされた方のユーザーで正しいinvite idを受け取った時に、エンターを押したら、ボタンと入力フィールドが再度表示されないように変更しました。(ここから再度別のidを受け取った時にbugる可能性があったため)
invite a Playerに適切なinvite idを入れた時に、再度invite idを入れることができない仕様になっていることを確認してください
about : #345 
close #345
=> [Game]invite id入力ボタン改善

backend/src/game/rewrite/game-rewrite.controller.ts, backend/src/game/rewrite/game-rewrite.dto.ts, backend/src/game/rewrite/game-rewrite.service.ts, frontend/src/features/game/GamePlayer1.tsx, frontend/src/features/game/GamePlayer2.tsx, frontend/src/features/game/JoinInvitedRoom.tsx, frontend/src/hooks/game/useInvitedRoom.ts
- game-rewriteの改修
- #352
about : #0
see also : #0
close #0
=> Rewrite game bug/issue352

backend/src/game/rewrite/game-rewrite.gateway.ts
- game-rewrite.gateway.ts handledisconnectの部分をgame-rewrite.serviceのdelete関数に変更
タスク番号4番
- #357
about : #356
see also: #352 
close #356
=> game-rewrite.gateway.ts handledisconnectの部分をgame-rewrite.serviceのdelete関数に変更

frontend/src/components/utils/Navbar.tsx, frontend/src/features/game/GamePlayer1.tsx, frontend/src/features/game/GamePlayer2.tsx, frontend/src/features/game/InviteRoom.tsx, frontend/src/features/game/JoinInvitedRoom.tsx
1.game-rewriteになっていなかった部分のrename
2.frontendの不要なボタンとコードの削除
about : #361
close #361
=> #361[delete]frontendの不要コード削除とrename to rewrite

backend/src/game/rewrite/game-rewrite.gateway.ts, backend/src/game/rewrite/game-rewrite.service.ts, docker/scripts/backend/entrypoint.sh
- 既にゲームに参加していた場合、そのゲームを返すように修正
- isOnGoingのnull checkを追加
- 
- #363 
about : #367 
close #367
=> ランダムゲームで既にPlayer2として参加していた場合、そのゲームを返す

backend/src/game/rewrite/game-rewrite.gateway.ts, backend/src/match/match.service.ts, frontend/src/features/game/GamePlayer1.tsx
- gameの修正
@kny-i 
コメントで書いたけど、matchの存在判定 は既に存在してたからそのままで大丈夫！
いくつかコメントでTODO書いたから、確認しながら実装お願いします
=> Game debug

frontend/src/features/game/GamePlayer1.tsx, frontend/src/features/game/GamePlayer2.tsx
ballのlevel up buttonを改善(これまでのmasterがlevelupしなかったのに対して、今回はするようになった)
=> Game ball fix

frontend/src/components/profile/MatchListButton.tsx, frontend/src/features/profile/MyProfile.tsx
- データベースのMatchのデータとProfileから表示されるMatchの履歴が同じにする。
- もしかしたらprisma周りでエラーが出るかもしれないけど、こんちゃんのPRが反映されたら直る予定！このPRはあくまでデータベースとの整合性を確認したほしい
- 
about : #0
see also : #0
close #0
=> Match list fix

backend/src/game/game.gateway.ts, backend/src/game/rewrite/game-rewrite.gateway.ts, backend/src/game/rewrite/game-rewrite.service.ts, backend/src/match/dto/match.dto.ts, backend/src/match/match.service.ts, frontend/src/features/game/GamePlayer1.tsx
Game edit 375の内容
masterからブランチ切ってスタート
about : #375 
see also : #375
close #375
=> Game edit 375の内容

frontend/src/features/game/GameMatching.tsx
=> conmentout observer

backend/src/game/rewrite/game-rewrite.gateway.ts, frontend/src/features/game/GamePlayer1.tsx
terminate_gameでデータベースを削除する際にservice内にある関数を利用した。
gamePlayer1.tsxのページ遷移の条件を取り除いた
game を操作する
inviteGame を操作する
=> Game delete/382
